<a href="https://colab.research.google.com/github/goldsp/Applied-Data-Science-Capstone-IBM-Coursera/blob/main/datathon01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Introdução**

Nesse **desafio**, propomos que a sua equipe seja a fração de Data & Analytics da ABCD, composta por analista de dados, cientista de dados, engenheiro de dados e analista de negócios. A sua equipe foi instada a desenvolver uma aplicação que automatize o processo de detecção de notícias falsas, vetor comumente utilizado para disseminar desinformação.

A fração de Data & Analytics tem por missão, a partir de um grande volume de dados, obter, processar e gerar insights sobre algum eixo ou linha de análise da Agenda de Produção, de modo a subsidiar as equipes responsáveis pela produção de conhecimentos.

Esse desafio será composto por quatro etapas:

    i. 	análise gráfica da base de dados e preparação para construção de modelo de detecção utilizando técnicas de aprendizado de máquina;
    ii. 	construção de dois modelos de aprendizado de máquina que automatizem a detecção de notícias falsas;
    iii.       estruturação de aplicação para detecção de notícias a partir da extração de mensagens em grupo do Telegram;
    iv. 	elaboração de dashboard no Power BI considerando resultados obtidos a partir do grupo do Telegram.

Ainda que haja um tipo profissional de dados melhor qualificado para desempenhar cada função em cada etapa,
é esperado e recomendado que a equipe compartilhe conhecimentos e proponha soluções de forma conjunta.
Apesar do “thon” (que remete a “marathon”), nesta primeira interação os vencedores não serão necessariamente aqueles que terminarem o desafio primeiro
(ainda que certamente este será critério de desempate).
Os integrantes das equipes poderão utilizar o **Google Colab** para elaborar as soluções. Sugere-se o **RocketChat** para comunicação entre os membros da equipe.

**2. Desenvolvimento do Desafio**

**2.1 Análise gráfica da base de dados e preparação para construção de modelo de detecção utilizando técnicas de aprendizado de máquina.**

A equipe recebeu em anexo os arquivos **‘train_data.csv’** e **‘train_labels.csv’**.
O arquivo **‘train_data.csv’** contém 6480 notícias verdadeiras ou falsas, sendo o respectivo rótulo indicado no arquivo **‘train_labels.csv’**. Já foi feito um primeiro preprocessamento nos textos das notícias (que não impede novas etapas de preprocessamento se assim a equipe julgar necessário).

A base de dados original utilizada está disponível no github (https://github.com/roneysco/Fake.br-Corpus/tree/master) e foi utilizada na tese de doutorado do Dr. Roney Lira de Sale Santos. A escolha da base de dados foi determinada por critérios estritamente didáticos, e a rotulação dos dados não foi validada pela ABCD.
Competirá principalmente ao analista de dados a análise exploratória gráfica da base de dados para gerar as primeiras impressões e informações sobre cada tipo de notícia.

Sugere-se as bibliotecas padrão do Python para esta finalidade, como Matplotlib, seaborn, pandas e plotly.
Além disso, o analista de dados deverá preparar a base de dados para ser utilizada pelo cientista de dados,
o que envolve preparação específica a partir do modelo escolhido por este último.
A avaliação dessa etapa se dará a partir da pertinência, completude e eficiência de código das visualizações geradas da base de dados.

**2.2 Construção de dois modelos de aprendizado de máquinas que automatizem a detecção de notícias falsas.**

A etapa seguinte, a ser tocada pelo cientista de dados, envolve o treinamento do modelo. Já tendo em mãos a base de dados de treino preparada pelo analista de dados,
o cientista de dados deverá desenvolver pelo menos dois modelos (note que a escolha do modelo pode implicar mudança no tratamento prévio da base de dados),
considerando diferentes cenários de inferência.
O cientista de dados deverá considerar dois cenários para inferência para definição dos modelos:
batch (quando há uma série de notícias a serem avaliadas simultaneamente) e streaming (uma notícia por vez, em tempo real).
Deverá haver justificativa para a escolha de cada modelo para as diferentes finalidades possíveis na atividade fim, e também devem constar as estatísticas de treino (report de classificação, matriz de confusão, etc.)

Finalmente, o cientista de dados deverá salvar os parâmetros do modelo treinado considerando inferência em streaming no formato ‘pickle’, que será utilizado na próxima etapa. Recomenda-se utilizar as bibliotecas mais consolidadas para machine learning, como sklearn, tensorflow e pytorch.

Não é necessário desenvolver soluções que envolvam poder computacional que exceda a capacidade do Google Colab gratuito.

A avaliação se dará com a performance dos modelos (não disponibilizamos parte da base de dados para verificar o poder de generalização dos modelos);
eficiência de código; escolha de cada modelo para qual finalidade.

**2.3 - Estruturação de aplicação para detecção de notícias a partir da extração de mensagens em grupo do Telegram**

Agora que o modelo já foi treinado é preciso analisar a performance dele em tempo real.
Em parceria com uma instituição parceira, a equipe de D&A recebeu informações sobre um grupo de Telegram em que há suspeita de desinformação.
Quando estiver em posse do modelo treinado, a equipe pode buscar representantes do desafio para obter o link do grupo.
O engenheiro de dados deverá desenvolver aplicação que acompanha constantemente o grupo designado.
Na ocorrência de uma mensagem nesse grupo, a aplicação deverá:
i) preprocessar o texto da mesma forma que na etapa 1;
ii) carregar os parâmetros do modelo treinado na etapa 2;
iii) realizar inferência no texto processado, gerando previsão de se a notícia é falsa ou não;
iv) salvar o texto, o timestamp de recebimento da mensagem, o timestamp após a realização da inferência e a previsão do modelo
para aquela notícia em um pandas dataframe;
v) ao fim do recebimento das mensagens (será indicado ao grupo), deverá salvar o pandas dataframe em formato .csv.
Recomenda-se a utilização da biblioteca python telethon, que é assíncrona (deve ser utilizada conjuntamente à biblioteca asyncio).
É possível utilizar a biblioteca no Google Colab (nesse caso, deve utilizar ainda o nest_asyncio).
Para utilizar a biblioteca telethon é necessário também obter os dados da API do Telegram,
que pode ser feito utilizadno esse link (https://core.telegram.org/api/obtaining_api_id).
Serão considerados na avaliação: intervalo de tempo entre o recebimento da mensagem e a realização da inferência; eficiência do código.

**2.4 - Elaboração de dashboard no Power BI considerando resultados obtidos a partir do grupo do Telegram**

O analista de BI tem por principal missão apresentar dados de forma a facilitar a tomada de decisão (data driven decision).
Os dados devem ser interativos para que seu destinatário observe nuances e tendências
de modo a facilitar o storytelling de sua produção de conhecimentos.

Assim, ele deverá compor um dashboard no Power BI a partir do arquivo .csv desenvolvido na fase anterior,
que será acrescido de informações fornecidas por insituição parceira do Sistema sobre as notícias que circularam no grupo de Telegram.
Quando estiverem prontos, peçam essas informações para os representantes do desafio.

A ideia do dashboard é permitir a rápida visualização do significado dos dados, especialmente de forma dinâmica,
com a existência de filtros por origem da informação (empresa), período e tema.
A demanda para a produção dos dashboards partiu da Unidade de produção de conhecimentos que trabalha com as seguintes áreas: (consultar documento original)

Nesse sentido, a fração observou a necessidade de saber se há um padrão, por origem, de envio de notícias falsas, com vistas a caracterizar alguma tática para afetar determinado público em horário. Além disso precisa de informações gerais para fácil visualização do grande volume constante de informações. Assim, o analista deverá prover informações do tipo:

    1) Widget sobre a emissão de notícias com filtro por hora e origem diferenciando as falsas das verdadeiras;
    2) Widget com a distribuição total de notícias com filtro por período e origem diferenciando as falsas das verdadeiras;
    3) Widget com a distribuição de fake news por tema;
    4) Widget que indique em que momento do dia há a maior distribuição de fake news em relação a notícias verdadeiras.
    5) Outros widgets que auxiliem a fração de produção de conhecimentos nos eixos supraindicados.

Além dos painéis em si, a equipe deverá informar as razões pelas quais escolheu o tipo de widget para seu storytelling.

Por fim, a equipe deverá auxiliar a equipe de engenharia e criar um widget que indique o intervalo de tempo, com filtro de período, de demora entre o recebimento da notícia e sua detecção pela ferramenta.

**3. Recursos (sugestões)**

Todos os recursos abaixo podem ser utilizados a partir da rede da ABCD lista abaixo é apenas exemplificativa.

Ambientes pra desenvolvimento
Google Colab (Internet), Power BI (Central de Software)
Bibliotecas python para processamento de linguagem natural
Nltk, matplotlib, seaborn, sklearn, wordcloud, spacy, gensim
Bibliotecas python para modelos de aprendizado de máquina
Sklearn, pytorch, tensorflow
Bibliotecas python para extração de mensagens do telegram
Telethon, nest_asyncio, asyncio
Ferramenta de mensageria/acompanhamento do desafio
RocketChat
Assistentes de inteligência artificial*
ChatGPT, Bard, HF Chat
Fóruns especializados
Kaggle, Reddit, Stackoverflow
* O uso de assistentes não é proibido, uma vez que fazem parte da rotina do analista de uma fração de D&A.
No entanto, para manter o caráter didático do desafio, será necessário e exigido entendimento da solução apresentada pelo assistente,
e as interações com o assistente deverão ser salvas e anexadas aos documentos do desafio.

**4. Da interação com representantes do Desafio**

O desafio em etapas gera a desvantagem de que se a equipe “travar” em uma das etapas, o resto pode ficar comprometido.
Cientes disso, os representantes do Datathon estarão acompanhando, dentro do possível, a discussão dentro dos grupos do RocketChat.
Caso haja percepção de que é necessário, os representantes darão dicas para as equipes de forma equânime e justa.
Os representantes ainda se esforçarão para conseguir tirar dúvidas que possam surgir durante o desafio.


**5. Da apresentação dos resultados**

Cada equipe deverá apresentar sua resposta ao desafio no dia 04/12.
Três equipes apresentarão no turno da manhã (das 10h às 12h) e uma no turno da tarde (a partir das 14h).
Caso haja alteração nos horários as equipes serão informadas previamente.
A apresentação deve versar sobre as informações e insights obtidos a partir da análise dos dados.
Não é necessário que se explique as ferramentas e algoritmos utilizados para chegar ao resultado do desafio.

**DESENVOLVIMENTO DA SOLUÇÃO**

In [48]:
!pip install transformers torch

import pandas as pd
import numpy as np
import time
import pickle
import pytz
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, precision_score
from datetime import datetime


#Leitura dos dados de treinamento
X = pd.read_csv("train_data.csv")
y = pd.read_csv("train_labels.csv")

#Exiba o os conjuntos de dados
pd.concat([X, y], axis=1).head()

preprocessed_news label
0  suica encontra contas ilicitas usadas abastece...  fake
1  genro silvio santos lista lava jato silvio san...  fake
2  linha credito imobiliario tera orcamento menor...  true
3  cerimonia oscar ultimo domingo mulheres roubar...  true
4  pais usa calor internet aquecer casas projeto ...  true

In [49]:
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

#Identificação das stop words
stop_words = set(stopwords.words("portuguese"))

'''
Durante a análise dos dados de treinamento foi verificado que algumas palavras
adicionais poderiam ser consideradas como stop words.
Essas palavras são adicionadas aqui.
'''
palavras_faltantes = ['acordo','ainda','anos','apos','ate','caso','contra','dia',
                      'disse','diz','durante','estao','ha','ja','nao','pessoas',
                      'pode','sao','so','sobre','tambem','ter','todos','vai']
                      #detectadas posteriormente que não estavam nas stop words

for w in palavras_faltantes:
    stop_words.add(w)

def remove_stopwords(text):
    if isinstance(text, str):
        words = text.split()
        return " ".join(word for word in words if word not in stop_words)
    else:
        return text

#Remove as step words do conjunto de dados
X['preprocessed_news']=X['preprocessed_news'].apply(remove_stopwords)

'''
O arquivo de dados parece já estar normalizado. Então essa etapa pode ser ignorada
'''
#Normalize o texto
#X = X.apply(lambda x: x.lower())

'''
Uso de TFIDF para medir e registrar a importância de cada palavra no contexto]
em que é usada
'''
#Vetorização dos textos com TFIDF
vectorizer = TfidfVectorizer(max_features=500000)
X_vectorized = vectorizer.fit_transform(X['preprocessed_news'])

X_vectorized.shape

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


(6480, 76262)

In [50]:
#stop_words é do tipo set
for w in stop_words:
  print(w, end=' ')
print ('\n \n número de palavras:', len(stop_words))

estávamos seríamos depois com pelos sejam teria houvéssemos tuas das me teriam tivéssemos às pela tem isso estivemos durante acordo ha nossa tambem minha seu será houvessem estas tiveram haja éramos teu diz seja era vos houverá que estes ao sejamos só mais houvesse haver foi estivéssemos pelas nem aquele estejam de seria somos delas tive tiverem tu houvera elas houveram deles houvermos minhas uma so terão houverem fossem estou mesmo houvéramos para houve serão as tenha até tinha disse serei não estar seremos eram pessoas muito eles nao te terei entre for nas aquela estavam tivessem estivesse houverão houverei teus fosse estiver fomos estao esteve por os seus estejamos vocês apos fôssemos nós ate este meu em estiverem estivessem estive formos meus ela aos dele essa a havemos na ser houvemos teremos sao forem hão aquilo houveriam sou teve anos fôramos da estamos teríamos você houver dela estivéramos mas numa ja aquelas também tenho tivemos sobre tua esta à tivera esse eu terá aqueles lhe

Analisar o array de vectorized

In [51]:
#Converte para uma matriz esparsa
X_dense = X_vectorized.toarray()

#Obte os nomes das palavras que correspondem às colunas
feature_names = vectorizer.get_feature_names_out()

#Cria o DataFrame
df1 = pd.DataFrame(X_dense, columns=feature_names)
df1['label']=y

#adicionar uma coluna com as notícias pré-processadas
df1['preprocessed_news'] = X['preprocessed_news'].values

In [52]:
df1['preprocessed_news']

0       suica encontra contas ilicitas usadas abastece...
1       genro silvio santos lista lava jato silvio san...
2       linha credito imobiliario tera orcamento menor...
3       cerimonia oscar ultimo domingo mulheres roubar...
4       pais usa calor internet aquecer casas projeto ...
                              ...                        
6475    lula gangue mortadelas sabemos brigar vamos co...
6476    aecio flagrado falando trafico drogas grampo t...
6477    claudia trevisan enviada especial nova york co...
6478    lula admitir chamado corrupto lula subiu tom a...
6479    lula intervencao forma temer pegar nicho bolso...
Name: preprocessed_news, Length: 6480, dtype: object

In [53]:
df1.head(20)

aa  aabb  aabertura  aace  aachen  aarhus  aaron  aashish   ab  abacaxi  \
0   0.0   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0      0.0   
1   0.0   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0      0.0   
2   0.0   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0      0.0   
3   0.0   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0      0.0   
4   0.0   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0      0.0   
5   0.0   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0      0.0   
6   0.0   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0      0.0   
7   0.0   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0      0.0   
8   0.0   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0      0.0   
9   0.0   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0      0.0   
10  0.0   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0      0.0   
11  0.0   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0      0.0   
12  0.0   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0      0.0   
13  0.0   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0      0.0   
14  0.0   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0      0.0   
15  0.0   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0      0.0   
16  0.0   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0      0.0   
17  0.0   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0      0.0   
18  0.0   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0      0.0   
19  0.0   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0      0.0   

    ...  zurique  zuum  zuza  zuzu  zveiter  zweig  zwi  zygmun  zygmunt  \
0   ...      0.0   0.0   0.0   0.0      0.0    0.0  0.0     0.0      0.0   
1   ...      0.0   0.0   0.0   0.0      0.0    0.0  0.0     0.0      0.0   
2   ...      0.0   0.0   0.0   0.0      0.0    0.0  0.0     0.0      0.0   
3   ...      0.0   0.0   0.0   0.0      0.0    0.0  0.0     0.0      0.0   
4   ...      0.0   0.0   0.0   0.0      0.0    0.0  0.0     0.0      0.0   
5   ...      0.0   0.0   0.0   0.0      0.0    0.0  0.0     0.0      0.0   
6   ...      0.0   0.0   0.0   0.0      0.0    0.0  0.0     0.0      0.0   
7   ...      0.0   0.0   0.0   0.0      0.0    0.0  0.0     0.0      0.0   
8   ...      0.0   0.0   0.0   0.0      0.0    0.0  0.0     0.0      0.0   
9   ...      0.0   0.0   0.0   0.0      0.0    0.0  0.0     0.0      0.0   
10  ...      0.0   0.0   0.0   0.0      0.0    0.0  0.0     0.0      0.0   
11  ...      0.0   0.0   0.0   0.0      0.0    0.0  0.0     0.0      0.0   
12  ...      0.0   0.0   0.0   0.0      0.0    0.0  0.0     0.0      0.0   
13  ...      0.0   0.0   0.0   0.0      0.0    0.0  0.0     0.0      0.0   
14  ...      0.0   0.0   0.0   0.0      0.0    0.0  0.0     0.0      0.0   
15  ...      0.0   0.0   0.0   0.0      0.0    0.0  0.0     0.0      0.0   
16  ...      0.0   0.0   0.0   0.0      0.0    0.0  0.0     0.0      0.0   
17  ...      0.0   0.0   0.0   0.0      0.0    0.0  0.0     0.0      0.0   
18  ...      0.0   0.0   0.0   0.0      0.0    0.0  0.0     0.0      0.0   
19  ...      0.0   0.0   0.0   0.0      0.0    0.0  0.0     0.0      0.0   

                                    preprocessed_news  
0   suica encontra contas ilicitas usadas abastece...  
1   genro silvio santos lista lava jato silvio san...  
2   linha credito imobiliario tera orcamento menor...  
3   cerimonia oscar ultimo domingo mulheres roubar...  
4   pais usa calor internet aquecer casas projeto ...  
5   operacao lava jato denunciou nesta jose dirceu...  
6   pgr recebe documento pedindo interdicao dilma ...  
7   violencia faz brasil viver processo desciviliz...  
8   eleicoes criar propagar boatos crime justica e...  
9   tv record mostra ascensao familia silva filho ...  
10  dizer respeitara decisao confirmou condenacao ...  
11  ana maria braga febre amarela matando macacos ...  

In [54]:
#separar as notícias verdadeiras das falsas em diferentes dataframes
df1_true=df1[0:0]
df1_fake=df1[0:0]

df1_true = df1[df1['label']=='true']
df1_fake = df1[df1['label']=='fake']

In [55]:
#Cria um dataframe com duas linhas - número de ocorrências e soma dos pesos TFID - para cada palavra
#de notícias verdadeiras no corpus
df_true=df1[0:0]

#Calcula a soma de cada coluna em df1
contagem_df1_true = ((df1_true != 0.0)).sum() #soma os 'trues' dos valores diferentes de zero
soma_df1_true = df1_true.sum()

#Adiciona essa soma como uma nova linha em df2
df_true = df_true.append(contagem_df1_true, ignore_index=True)
df_true = df_true.append(soma_df1_true, ignore_index=True)
df_true.drop('preprocessed_news', axis=1, inplace=True)

<ipython-input-55-014bb2289048>:10: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_true = df_true.append(contagem_df1_true, ignore_index=True)
<ipython-input-55-014bb2289048>:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_true = df_true.append(soma_df1_true, ignore_index=True)


In [56]:
df_true.head(20)

aa      aabb  aabertura      aace    aachen    aarhus     aaron  \
0  6.000000  1.000000   1.000000  1.000000  1.000000  1.000000  3.000000   
1  0.294537  0.125251   0.061621  0.076033  0.045641  0.027964  0.087988   

    aashish        ab  abacaxi  ...   zurcher   zurique      zuum      zuza  \
0  1.000000  1.000000  6.00000  ...  1.000000  4.000000  1.000000  1.000000   
1  0.113704  0.081557  0.23023  ...  0.248295  0.206869  0.041556  0.041316   

       zuzu   zveiter     zweig       zwi    zygmun   zygmunt  
0  1.000000  18.00000  2.000000  8.000000  1.000000  4.000000  
1  0.049338   1.47183  0.096392  0.628693  0.014523  0.242862  

[2 rows x 76262 columns]

In [57]:
#Cria um dataframe com duas linhas - número de ocorrências e soma dos pesos TFID - para cada palavra
#de notícias falsas no corpus
df_fake=df1[0:0]

contagem_df1_fake = ((df1_fake != 0.0) ).sum() #soma os 'fakes' dos valores diferentes de zero
soma_df1_fake = df1_fake.sum()

df_fake = df_fake.append(contagem_df1_fake, ignore_index=True)
df_fake = df_fake.append(soma_df1_fake, ignore_index=True)

df_fake.drop('preprocessed_news', axis=1, inplace=True)


<ipython-input-57-0016e1ff1b98>:8: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_fake = df_fake.append(contagem_df1_fake, ignore_index=True)
<ipython-input-57-0016e1ff1b98>:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_fake = df_fake.append(soma_df1_fake, ignore_index=True)


In [58]:
df_fake.head(20)


aa  aabb  aabertura  aace  aachen  aarhus  aaron  aashish   ab  \
0  1.000000   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0   
1  0.177576   0.0        0.0   0.0     0.0     0.0    0.0      0.0  0.0   

   abacaxi  ...  zurcher  zurique  zuum  zuza  zuzu   zveiter  zweig  \
0      0.0  ...      0.0      0.0   0.0   0.0   0.0  1.000000    0.0   
1      0.0  ...      0.0      0.0   0.0   0.0   0.0  0.075165    0.0   

        zwi  zygmun  zygmunt  
0  2.000000     0.0      0.0  
1  0.493339     0.0      0.0  

[2 rows x 76262 columns]

In [59]:
#trasnposição dos dataframes
df_true=df_true.T
df_fake=df_fake.T

In [60]:
#inclusão da palavra índice no dataframe
df_true['palavra']=df_true.index
df_fake['palavra']=df_fake.index



In [61]:
#renomeia as colunas quantidade e soma
if 'label' in df_true['palavra']:
  df_true.drop('label', axis=0, inplace=True)
df_true = df_true.rename(columns={0: 'quantidade'})
df_true = df_true.rename(columns={1: 'soma'})

df_true = df_true[df_true['soma'] != 0.0]
df_true.sort_values(by='quantidade', ascending=False).head(20)

quantidade       soma     palavra
segundo        2311.0  66.931662     segundo
presidente     1945.0  92.489133  presidente
federal        1907.0  82.185321     federal
ano            1761.0  51.532548         ano
dois           1706.0  42.106949        dois
pais           1676.0  51.356242        pais
governo        1673.0  73.773514     governo
afirmou        1641.0  55.881168     afirmou
nesta          1641.0  47.032443       nesta
outros         1576.0  33.511909      outros
alem           1555.0  33.840278        alem
porque         1542.0   42.14036      porque
publico        1530.0  44.272419     publico
brasil         1518.0  55.486432      brasil
desde          1502.0  33.051658       desde
parte          1490.0  31.985726       parte
fazer          1475.0  36.102875       fazer
justica        1458.0  51.320866     justica
estado         1447.0  48.032998      estado
antes          1365.0  30.393209       antes

In [62]:
df_true.sort_values(by='soma', ascending=False).head(20)

quantidade        soma     palavra
lula            914.0  115.635718        lula
presidente     1945.0   92.489133  presidente
temer           977.0   87.767102       temer
federal        1907.0   82.185321     federal
governo        1673.0   73.773514     governo
segundo        2311.0   66.931662     segundo
ministro       1109.0    57.39257    ministro
lava           1060.0    56.59501        lava
jato           1067.0   56.121742        jato
afirmou        1641.0   55.881168     afirmou
brasil         1518.0   55.486432      brasil
defesa         1220.0   53.281447      defesa
ano            1761.0   51.532548         ano
pais           1676.0   51.356242        pais
justica        1458.0   51.320866     justica
odebrecht       477.0    50.17986   odebrecht
policia        1193.0   49.686937     policia
estado         1447.0   48.032998      estado
decisao        1118.0   47.747509     decisao
tribunal       1231.0   47.546428    tribunal

In [63]:
if 'label' in df_fake['palavra']:
  df_fake.drop('label', axis=0, inplace=True)
df_fake = df_fake.rename(columns={0: 'quantidade'})
df_fake = df_fake.rename(columns={1: 'soma'})
df_fake = df_fake[df_fake['soma'] != 0.0]

df_fake.sort_values(by='quantidade', ascending=False).head(20)

quantidade        soma     palavra
presidente      942.0   53.625857  presidente
lula            863.0  119.147439        lula
pais            793.0   39.632695        pais
brasil          790.0   43.813476      brasil
federal         706.0   36.083353     federal
dilma           689.0   80.946846       dilma
governo         666.0    37.71239     governo
hoje            644.0   29.766875        hoje
sera            503.0    27.68556        sera
pt              482.0   38.664522          pt
video           452.0   38.936385       video
petista         444.0   32.190004     petista
temer           435.0   51.114039       temer
dinheiro        429.0   27.523448    dinheiro
tudo            404.0   21.859302        tudo
milhoes         404.0   30.503511     milhoes
ministro        402.0   36.672767    ministro
agora           394.0   18.640144       agora
fez             393.0   17.987562         fez
sergio          391.0   34.856737      sergio

In [64]:
df_fake.sort_values(by='soma', ascending=False).head(20)

quantidade        soma     palavra
lula            863.0  119.147439        lula
dilma           689.0   80.946846       dilma
presidente      942.0   53.625857  presidente
temer           435.0   51.114039       temer
moro            329.0   43.967565        moro
brasil          790.0   43.813476      brasil
pais            793.0   39.632695        pais
video           452.0   38.936385       video
pt              482.0   38.664522          pt
governo         666.0    37.71239     governo
ministro        402.0   36.672767    ministro
federal         706.0   36.083353     federal
coreia          163.0   35.196959      coreia
sergio          391.0   34.856737      sergio
petista         444.0   32.190004     petista
cunha           147.0   30.579701       cunha
milhoes         404.0   30.503511     milhoes
hoje            644.0   29.766875        hoje
deputado        289.0   29.218803    deputado
juiz            324.0   28.804422        juiz

In [65]:
df_true.describe()

quantidade          soma palavra
count      71258.0  71258.000000   71258
unique       728.0  47657.000000   71258
top            1.0      0.019333      aa
freq       30079.0    138.000000       1

In [66]:
df_fake.describe()

quantidade          soma palavra
count      30339.0  30339.000000   30339
unique       290.0  26374.000000   30339
top            1.0      0.037427      aa
freq       13646.0     32.000000       1

Dados mostram que as notícias falsas possuem um vocabulário bem reduzido em relação às notícias verdadeiras.

Algumas ideias para a etapa de análise dos dados:
- análise de clusters para identificar possíveis temas das notícias: política, saúde, religião, segurança pública, economia e finanças, entretenimento, etc.
- ver se é possível identificar o potencial de dano das notícias (nível de propagação, capacidade de convencimento, impactos, etc)e se é possível correlacionar esse potencial de dano  à proporção de palavras/frases/tokens.



**Divisão em conjunto de testes e conjunto de treinamento**

In [67]:
#Divida o conjunto de dados em um conjunto de treinamento e um conjunto de teste
X_train, X_test, y_train, y_test = train_test_split(X_vectorized, y, test_size=0.3)

In [90]:
#salva o modelo
def save_model(model,model_name):
  horario_de_brasilia = pytz.timezone('America/Sao_Paulo')
  agora = datetime.now(horario_de_brasilia).strftime('%Y-%m-%d-%H-%M-%S')
  arquivo = f'{model_name}_{agora}.pkl'
  pickle.dump(model, open(arquivo, 'wb'))

#relatorio do modelo
def model_report(title, accuracy, precision, conf_matrix, execution_time):
  print(title)
  print(f"Acurácia: {accuracy}")
  print(f"Precisão: {precision}")
  print("Matriz de Confusão:")
  print(conf_matrix)
  print(f"\nTempo de execução: {execution_time} segundos")

#relatorio da validacao cruzada
def model_report_cv(title,scores,executionr_time):
  print(title)
  print(f"Scores for each fold are: {scores}")
  print(f"Average score: {scores.mean()}")
  print(f"\nTempo de execução: {execution_time} segundos")

**Treinamento com Regressão Logística**

In [91]:
#regressão logística

start_time = time.time()  #Timestamp de início

model = LogisticRegression()
model.fit(X_train, y_train.values.ravel())  #Usando .ravel() para transformar y_train em um array 1D, senão dá um erro

#previsão e avaliação
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, pos_label='fake')
conf_matrix = confusion_matrix(y_test, y_pred)

end_time = time.time()  #Timestamp de término
execution_time = end_time - start_time  #Cálculo do tempo de execução

#salva o modelo
save_model(model,'lr')

#relatorio da execução
model_report('Regressão logística', accuracy, precision, conf_matrix, execution_time)

Regressão logística
Acurácia: 0.9439300411522634
Precisão: 0.934010152284264
Matriz de Confusão:
[[920  44]
 [ 65 915]]

Tempo de execução: 2.2659080028533936 segundos


'''
#código para usar o modelo salvo
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(X_test)
'''

In [92]:
#validação cruzada
start_time = time.time()  #Timestamp de início

#número de dobras
n_folds = 5
scores = cross_val_score(model, X_vectorized, y.values.ravel(), cv=n_folds, scoring='accuracy')
end_time = time.time()  #Timestamp de término
execution_time = end_time - start_time  #Cálculo do tempo de execução

model_report_cv(f"Validação cruzada - regressão logísitca com {n_folds} dobras",scores,execution_time)

Validação cruzada - regressão logísitca com 5 dobras
Scores for each fold are: [0.94675926 0.94444444 0.9367284  0.94753086 0.9529321 ]
Average score: 0.945679012345679

Tempo de execução: 8.430888652801514 segundos


**Regressão Logísitica com regularização Ridge**





In [104]:
from sklearn.linear_model import RidgeClassifier

#regularização Ridge
start_time = time.time()  #Timestamp de início

alpha=2.0
ridge_model = RidgeClassifier(alpha=alpha)
ridge_model.fit(X_train, y_train.values.ravel())

#previsão e avaliação
y_pred_ridge = ridge_model.predict(X_test)

accuracy_ridge = accuracy_score(y_test, y_pred_ridge)
precision_ridge = precision_score(y_test, y_pred_ridge, pos_label='fake')
conf_matrix_ridge = confusion_matrix(y_test, y_pred_ridge)

end_time = time.time()  #Timestamp de término
execution_time = end_time - start_time  #Cálculo do tempo de execução

#salva o modelo
save_model(model,'ridge')

#relatorio da execução
model_report(f'Regressão logística com regularização Ridge alpha={alpha}', accuracy_ridge, precision_ridge, conf_matrix_ridge, execution_time)

Regressão logística com regularização Ridge alpha=2.0
Acurácia: 0.9552469135802469
Precisão: 0.9433771486349848
Matriz de Confusão:
[[933  31]
 [ 56 924]]

Tempo de execução: 0.25702786445617676 segundos


In [105]:
#validação cruzada
start_time = time.time()  #Timestamp de início

#número de folds (por exemplo, 5)
n_folds = 5
scores = cross_val_score(ridge_model, X_vectorized, y.values.ravel(), cv=n_folds, scoring='accuracy')

end_time = time.time()  #Timestamp de término
execution_time = end_time - start_time  #Cálculo do tempo de execução

model_report_cv(f"Validação cruzada - regressão logística com {n_folds} dobras e regularização Ridge alpha={alpha}",scores,execution_time)

Validação cruzada - regressão logística com 5 dobras e regularização Ridge alpha=2.0
Scores for each fold are: [0.96064815 0.95524691 0.94675926 0.96219136 0.96064815]
Average score: 0.9570987654320987

Tempo de execução: 1.3395180702209473 segundos


**Regressão Logísitica com regularização Lasso**

In [117]:
from sklearn.linear_model import Lasso

start_time = time.time()  #Timestamp de início

#Converte o rótulo 'fake' para 1 e 'true' para 0
y_train_num = np.where(y_train.values.ravel() == 'fake', 1, 0)
y_test_num = np.where(y_test.values.ravel() == 'fake', 1, 0)

#Treina o modelo com regularização Lasso
#lasso_model = Lasso()

lasso_model = LogisticRegression(penalty="l1", C=0.82, solver="liblinear")
lasso_model.fit(X_train, y_train_num)

#previsão e avaliação
y_pred_lasso = lasso_model.predict(X_test) > 0.5  #Usando 0.5 como limiar para classificação

accuracy_lasso = accuracy_score(y_test_num, y_pred_lasso)
precision_lasso = precision_score(y_test_num, y_pred_lasso)
conf_matrix_lasso = confusion_matrix(y_test_num, y_pred_lasso)

end_time = time.time()  #Timestamp de término
execution_time = end_time - start_time  #Cálculo do tempo de execução

#salva o modelo
save_model(model,'lasso')

#relatorio da execução
model_report(f'Regressão logística com regularização Lasso', accuracy_lasso, precision_lasso, conf_matrix_lasso, execution_time)


Regressão logística com regularização Lasso
Acurácia: 0.9017489711934157
Precisão: 0.8988648090815273
Matriz de Confusão:
[[882  98]
 [ 93 871]]

Tempo de execução: 0.227492094039917 segundos


A regularização não produziu ganho em relação à Regressão Logísitica não regularizada.

**SVM**

In [119]:
from sklearn.svm import SVC

start_time = time.time()  #Timestamp de início
#Treinar o SVM
svm_model = SVC()
svm_model.fit(X_train, y_train.values.ravel())  #Usando .ravel() para transformar y_train em um array 1D

#previsão e avaliação
y_pred = svm_model.predict(X_test)

accuracy_svm = accuracy_score(y_test, y_pred)
precision_svm = precision_score(y_test, y_pred, pos_label='fake')
conf_matrix_svm = confusion_matrix(y_test, y_pred)

end_time = time.time()  #Timestamp de término
execution_time = end_time - start_time  #Cálculo do tempo de execução

#salva o modelo
save_model(model,'svm')

#relatorio da execução
model_report(f'SVM', accuracy_svm, precision_svm, conf_matrix_svm, execution_time)

SVM
Acurácia: 0.9475308641975309
Precisão: 0.9353535353535354
Matriz de Confusão:
[[926  38]
 [ 64 916]]

Tempo de execução: 47.694265365600586 segundos


In [120]:
start_time = time.time()  #Timestamp de início

#validação cruzada
#Defina o número de folds (por exemplo, 5)
n_folds = 5
scores = cross_val_score(svm_model, X_vectorized, y.values.ravel(), cv=n_folds, scoring='accuracy')

end_time = time.time()  #Timestamp de término
execution_time = end_time - start_time  #Cálculo do tempo de execução

model_report_cv(f"Validação cruzada - SVM {n_folds} dobras",scores,execution_time)

Validação cruzada - SVM 5 dobras
Scores for each fold are: [0.95910494 0.94984568 0.94058642 0.95601852 0.95756173]
Average score: 0.9526234567901234

Tempo de execução: 272.03007555007935 segundos


Não houve ganho significativo em relação à Regressão Logística e o tempo de treinamento foi bem maior: 58 segundos com CPU.

**Decision Tree**

In [122]:
from sklearn.tree import DecisionTreeClassifier

start_time = time.time()  #Timestamp de início

#Ler arquivos csv
X = pd.read_csv("train_data.csv")
y = pd.read_csv("train_labels.csv")

#Vetorização dos textos com TFIDF
vectorizer = TfidfVectorizer(max_features=500000)  #Considerando o número elevado de características
X_vectorized = vectorizer.fit_transform(X['preprocessed_news'])  #Substitua 'preprocessed_news' pelo nome correto da coluna

#Divide o conjunto de dados treinamento e teste
X_train, X_test, y_train, y_test = train_test_split(X_vectorized, y, test_size=0.3)

#Parâmetros para controlar a complexidade da árvore
max_depth = 10  #Ajuste para evitar overfitting
min_samples_split = 8  #Número mínimo de amostras para dividir um nó
min_samples_leaf = 5  #Número mínimo de amostras para ser um nó folha

#Treina o modelo de Árvore de Decisão com parâmetros para evitar overfitting
tree_model = DecisionTreeClassifier(max_depth=max_depth,
                                    min_samples_split=min_samples_split,
                                    min_samples_leaf=min_samples_leaf)
tree_model.fit(X_train, y_train.values.ravel())  #Usando .ravel() para transformar y_train em um array 1D

#previsão e avaliação
y_pred = tree_model.predict(X_test)

accuracy_tree = accuracy_score(y_test, y_pred)
precision_tree = precision_score(y_test, y_pred, pos_label='fake')
conf_matrix_tree = confusion_matrix(y_test, y_pred)

end_time = time.time()  #Timestamp de término
execution_time = end_time - start_time  #Cálculo do tempo de execução

#salva o modelo
save_model(model,'tree')

#relatorio da execução
model_report(f'Decision Tree - maxdepth={max_depth}, min_samples_split={min_samples_split} e min_samples_leaf={min_samples_leaf} ',
             accuracy_tree, precision_tree, conf_matrix_tree, execution_time)

Decision Tree - maxdepth=10, min_samples_split=8 e min_samples_leaf=5 
Acurácia: 0.8940329218106996
Precisão: 0.8891170431211499
Matriz de Confusão:
[[866  98]
 [108 872]]

Tempo de execução: 4.561434268951416 segundos


In [123]:
start_time = time.time()  #Timestamp de início

#validação cruzada
#Define o número de folds (por exemplo, 5)
n_folds = 5
scores = cross_val_score(tree_model, X_vectorized, y.values.ravel(), cv=n_folds, scoring='accuracy')

end_time = time.time()  #Timestamp de término
execution_time = end_time - start_time  #Cálculo do tempo de execução

model_report_cv(f"Decision Tree com validação cruzada {n_folds} dobras",scores,execution_time)

Decision Tree com validação cruzada 5 dobras
Scores for each fold are: [0.89814815 0.88040123 0.91126543 0.89429012 0.88425926]
Average score: 0.8936728395061729

Tempo de execução: 12.697639226913452 segundos


Acurácia e precisão bem pior que LR e SVM. Tempo de execução com CPU: 8 a 9 segundos.

**Random Forest**

In [126]:
from sklearn.ensemble import RandomForestClassifier

start_time = time.time()  #Timestamp de início

#Parâmetros para a Floresta Aleatória
n_estimators = 100  #Número de árvores na floresta
#ajustei os próximos parâmetros de acordo com o melhor desempenho no modelo Decision Tree
max_depth = 200  #Profundidade máxima de cada árvore
min_samples_split = 8  #Número mínimo de amostras para dividir um nó
min_samples_leaf = 5  #Número mínimo de amostras para ser um nó folha

#Treina o modelo de Floresta Aleatória
forest_model = RandomForestClassifier(n_estimators=n_estimators,
                                      max_depth=max_depth,
                                      min_samples_split=min_samples_split,
                                      min_samples_leaf=min_samples_leaf)
forest_model.fit(X_train, y_train.values.ravel())  #Usando .ravel() para transformar y_train em um array 1D

#previsão e avaliação
y_pred = forest_model.predict(X_test)

accuracy_rf = accuracy_score(y_test, y_pred)
precision_rf = precision_score(y_test, y_pred, pos_label='fake')
conf_matrix_rf = confusion_matrix(y_test, y_pred)

end_time = time.time()  #Timestamp de término
execution_time = end_time - start_time  #Cálculo do tempo de execução

#salva o modelo
save_model(model,'rf')

#relatorio da execução
model_report(f'Random Forest - estimators={n_estimators}, maxdepth={max_depth}, min_samples_split={min_samples_split} e min_samples_leaf={min_samples_leaf} ',
              accuracy_rf, precision_rf, conf_matrix_rf, execution_time)




Random Forest - estimators=100, maxdepth=200, min_samples_split=8 e min_samples_leaf=5 
Acurácia: 0.9444444444444444
Precisão: 0.9246031746031746
Matriz de Confusão:
[[932  32]
 [ 76 904]]

Tempo de execução: 3.7443783283233643 segundos


In [128]:
start_time = time.time()  #Timestamp de início

#validação cruzada
#Defina o número de folds (por exemplo, 5)
n_folds = 5
scores = cross_val_score(forest_model, X_vectorized, y.values.ravel(), cv=n_folds, scoring='accuracy')

end_time = time.time()  #Timestamp de término
execution_time = end_time - start_time  #Cálculo do tempo de execução

model_report_cv(f"Random Forest - estimators={n_estimators}, maxdepth={max_depth}, min_samples_split={min_samples_split} e min_samples_leaf={min_samples_leaf} com validação cruzada {n_folds} dobras",scores,execution_time)


Random Forest - estimators=100, maxdepth=200, min_samples_split=8 e min_samples_leaf=5 com validação cruzada 5 dobras
Scores for each fold are: [0.94521605 0.94830247 0.95216049 0.94598765 0.95138889]
Average score: 0.9486111111111111

Tempo de execução: 22.536035299301147 segundos


**KNN**

In [129]:
from sklearn.neighbors import KNeighborsClassifier
start_time = time.time()  #Timestamp de início

#Parâmetros para o modelo KNN
n_neighbors = 5  #Número de vizinhos a serem considerados

#Treina o  KNN
knn_model = KNeighborsClassifier(n_neighbors=n_neighbors)
knn_model.fit(X_train, y_train.values.ravel())  #Usando .ravel() para transformar y_train em um array 1D

#previsão e avaliação
y_pred = knn_model.predict(X_test)

accuracy_knn = accuracy_score(y_test, y_pred)
precision_knn = precision_score(y_test, y_pred, pos_label='fake')
conf_matrix_knn = confusion_matrix(y_test, y_pred)

end_time = time.time()  #Timestamp de término
execution_time = end_time - start_time  #Cálculo do tempo de execução

#salva o modelo
save_model(model,'knn')

#relatorio da execução
model_report(f'KNN - k={n_neighbors} ',
              accuracy_knn, precision_knn, conf_matrix_knn, execution_time)




KNN - k=5 
Acurácia: 0.7026748971193416
Precisão: 0.8725868725868726
Matriz de Confusão:
[[452 512]
 [ 66 914]]

Tempo de execução: 115.2996609210968 segundos


In [130]:
from sklearn.neighbors import KNeighborsClassifier
start_time = time.time()  #Timestamp de início

#Parâmetros para o modelo KNN
n_neighbors = 4  #Número de vizinhos a serem considerados

#Treina o  KNN
knn_model = KNeighborsClassifier(n_neighbors=n_neighbors)
knn_model.fit(X_train, y_train.values.ravel())  #Usando .ravel() para transformar y_train em um array 1D

#previsão e avaliação
y_pred = knn_model.predict(X_test)

accuracy_knn = accuracy_score(y_test, y_pred)
precision_knn = precision_score(y_test, y_pred, pos_label='fake')
conf_matrix_knn = confusion_matrix(y_test, y_pred)

end_time = time.time()  #Timestamp de término
execution_time = end_time - start_time  #Cálculo do tempo de execução

#salva o modelo
save_model(model,'knn')

#relatorio da execução
model_report(f'KNN - k={n_neighbors} ',
              accuracy_knn, precision_knn, conf_matrix_knn, execution_time)

KNN - k=4 
Acurácia: 0.7505144032921811
Precisão: 0.8321775312066574
Matriz de Confusão:
[[600 364]
 [121 859]]

Tempo de execução: 116.47654366493225 segundos


**Naive Bayes**

In [131]:
from sklearn.naive_bayes import MultinomialNB

start_time = time.time()  #Timestamp de início

#Treina o modelo Naive Bayes
nb_model = MultinomialNB()
nb_model.fit(X_train, y_train.values.ravel())  #Usando .ravel() para transformar y_train em um array 1D

#previsão e avaliação
y_pred = nb_model.predict(X_test)

accuracy_mnb = accuracy_score(y_test, y_pred)
precision_mnb = precision_score(y_test, y_pred, pos_label='fake')
conf_matrix_mnb = confusion_matrix(y_test, y_pred)

end_time = time.time()  #Timestamp de término
execution_time = end_time - start_time  #Cálculo do tempo de execução

#salva o modelo
save_model(model,'mnb')

#relatorio da execução
model_report(f'Naive Bayes',
              accuracy_mnb, precision_mnb, conf_matrix_mnb, execution_time)


Naive Bayes
Acurácia: 0.5992798353909465
Precisão: 0.9894179894179894
Matriz de Confusão:
[[187 777]
 [  2 978]]

Tempo de execução: 0.06152009963989258 segundos


**Voting Classificator - LR, SVM e MNB**

In [132]:
from sklearn.ensemble import VotingClassifier

start_time = time.time()  #Timestamp de início
#Modelos individuais para o ensemble
model1 = LogisticRegression()
model2 = SVC(probability=True)  #O parâmetro probability=True é necessário para o VotingClassifier
model3 = MultinomialNB()

#Ensemble: Voting Classifier
ensemble_model = VotingClassifier(estimators=[('lr', model1), ('svc', model2), ('nb', model3)], voting='soft')
ensemble_model.fit(X_train, y_train.values.ravel())  #Usando .ravel() para transformar y_train em um array 1D

#previsão e avaliação
y_pred = ensemble_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, pos_label='fake')
conf_matrix = confusion_matrix(y_test, y_pred)

end_time = time.time()  #Timestamp de término
execution_time = end_time - start_time  #Cálculo do tempo de execução

#salva o modelo
save_model(model,'lr_svm_mnb')

#relatorio da execução
model_report(f'Ensemble Voting Classificator - LR, SVM e MNB',
              accuracy, precision, conf_matrix, execution_time)

Ensemble Voting Classificator - LR, SVM e MNB
Acurácia: 0.940843621399177
Precisão: 0.9619151251360174
Matriz de Confusão:
[[884  80]
 [ 35 945]]

Tempo de execução: 194.264990568161 segundos


**Voting Classificator - Ridge, SVM e Random Forest**

In [133]:
start_time = time.time()  #Timestamp de início


#Modelos individuais para o ensemble
ridge_model = RidgeClassifier()
svc_model = SVC(probability=True)  #O parâmetro probability=True é necessário para o VotingClassifier
rf_model = RandomForestClassifier()

#Ensemble: Voting Classifier
ensemble_model = VotingClassifier(estimators=[
    ('ridge', ridge_model),
    ('svc', svc_model),
    ('rf', rf_model)
], voting='hard')
ensemble_model.fit(X_train, y_train.values.ravel())  #Usando .ravel() para transformar y_train em um array 1D

#previsão e avaliação
y_pred = ensemble_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, pos_label='fake')
conf_matrix = confusion_matrix(y_test, y_pred)

end_time = time.time()  #Timestamp de término
execution_time = end_time - start_time  #Cálculo do tempo de execução

#salva o modelo
save_model(model,'ridge_svm_rf')

#relatorio da execução
model_report(f'Ensemble Voting Classificator - Ridge, SVM e Random Forest',
              accuracy, precision, conf_matrix, execution_time)

Ensemble Voting Classificator - Ridge, SVM e Random Forest
Acurácia: 0.948045267489712
Precisão: 0.9242871189773845
Matriz de Confusão:
[[940  24]
 [ 77 903]]

Tempo de execução: 199.6010046005249 segundos


In [73]:
X

preprocessed_news
0     suica encontra contas ilicitas usadas abastece...
1     genro silvio santos lista lava jato silvio san...
2     linha credito imobiliario tera orcamento menor...
3     cerimonia oscar ultimo domingo mulheres roubar...
4     pais usa calor internet aquecer casas projeto ...
...                                                 ...
6475  lula gangue mortadelas sabemos brigar vamos co...
6476  aecio flagrado falando sobre trafico drogas gr...
6477  claudia trevisan enviada especial nova york co...
6478  lula diz nao vai admitir ser chamado corrupto ...
6479  lula diz intervencao forma temer pegar nicho b...

[6480 rows x 1 columns]

**Deep Learning**

Redes Neurais Densas
Redes Neurais Convolucionais (CNNs) para Texto:
Redes Neurais Recorrentes (RNNs), incluindo LSTM e GRU:
Transformers e Modelos Pré-Treinados (como BERT, GPT):
Redes Neurais Autoencoder para Redução de Dimensionalidade:

Redes Neurais Densas
Redes Neurais Convolucionais (CNNs) para Texto:
Redes Neurais Recorrentes (RNNs), incluindo LSTM e GRU:
Transformers e Modelos Pré-Treinados (como BERT, GPT):
Redes Neurais Autoencoder para Redução de Dimensionalidade:

In [134]:
#Dica do Alexandre: Deep Metric Learning com KNN

'''from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import pandas as pd'''
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, GlobalAveragePooling1D, Dense
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam


start_time = time.time()  #Timestamp de início
#
MAX_NUM_WORDS = 10000
MAX_SEQUENCE_LENGTH = 7000
EMBEDDING_DIM = 50

#Learning rate - diminuir o tamanho do passo na avaliação da função de perda andar mais devagar (intervalo menor)
#mas pode exigir mais epochs
learning_rate = 0.0005

#Leitura dos dados
X = pd.read_csv("train_data.csv")["preprocessed_news"]
y = pd.read_csv("train_labels.csv")['label']

#Converter as labels para valores numéricos
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

#Tokenização e padding
tokenizer = Tokenizer(num_words=MAX_NUM_WORDS)
tokenizer.fit_on_texts(X)
sequences = tokenizer.texts_to_sequences(X)
X_padded = pad_sequences(sequences, maxlen=MAX_SEQUENCE_LENGTH)

print("Formato de X_padded:", X_padded.shape)
print("Formato de y_encoded:", y_encoded.shape)

#Se y_encoded não for um array, ou se tiver uma dimensão incorreta, corrigir
if len(y_encoded.shape) == 1:
    y_encoded = y_encoded.reshape(-1, 1)
elif len(y_encoded.shape) > 2:
    y_encoded = y_encoded.squeeze()  #Reduz a dimensão, se necessário

#divisão dos dados
X_train, X_temp, y_train, y_temp = train_test_split(X_padded, y_encoded, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)


#Construção do modelo de Deep Learning
model = Sequential()
model.add(Embedding(MAX_NUM_WORDS, EMBEDDING_DIM, input_length=MAX_SEQUENCE_LENGTH))
model.add(GlobalAveragePooling1D())
model.add(Dense(EMBEDDING_DIM, activation='relu')) #relu performou melhor que gelu
#model.add(Dense(EMBEDDING_DIM, activation='gelu'))
model.add(Dense(len(y.unique()), activation='softmax'))  #Use a quantidade de classes únicas em y

#model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
#model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])

optimizer = Adam(learning_rate=learning_rate)

#Compilação do modelo com o otimizador configurado
model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])

#Treinamento do modelo
#epochs=46 foi a melhor função de perda para não sobreajustar
model.fit(X_train, to_categorical(y_train),
          batch_size=32,
          epochs=46,
          validation_data=(X_val, to_categorical(y_val)))  #Usando o conjunto de validação

#Extração de representações
extractor = tf.keras.Model(inputs=model.inputs, outputs=model.layers[-2].output)
X_train_features = extractor.predict(X_train)
X_test_features = extractor.predict(X_test)

NameError: ignored

In [110]:
#Treinamento do KNN com as representações aprendidas
knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train_features, y_train)

#Avaliação do modelo KNN
y_pred = knn.predict(X_test_features)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)


end_time = time.time()  #Timestamp de término
execution_time = end_time - start_time  #Cálculo do tempo de execução

#salva o modelo
save_model(model,'dml_knn')

#relatorio da execução
model_report(f'KNN com Deep Metric Learning',
              accuracy, precision, conf_matrix, execution_time)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNN com Deep Metric Learning
Acurácia: 0.9619341563786008
Precisão: 0.9515151515151515
Matriz de Confusão:
[[464  24]
 [ 13 471]]

Tempo de execução: 6141.169019460678 segundos


Verificar:

Uso de validação cruzada.
Redução de dimensionalidade com autoencoder

Dica do Alexandre: Deep Metric Learning com KNN